name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: SetUp Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15
    - name: Install dependencies    
      working-directory: ./codebase/rdicidr-0.1.0
      run: npm install

    - name: Run ESLint   
      working-directory: ./codebase/rdicidr-0.1.0
      run: npm run lint
    
    - name: Run Prettier   
      working-directory: ./codebase/rdicidr-0.1.0
      run: npm install --save-dev Prettier

    - name: Run Prettier2   
      working-directory: ./codebase/rdicidr-0.1.0
      run: npm run prettier -- --write

    - name: Run Test 
      working-directory: ./codebase/rdicidr-0.1.0
      run: CI=true npm run test

    - name: Run build
      working-directory: ./codebase/rdicidr-0.1.0
      run: CI=true npm run build

